### ISSUE TITLE
docker installation instructions?

### ISSUE THREAD

**Issue by InstanceOfMichael** [e-alfred/ocdownloader#215]
I installed via the docker method: https://hub.docker.com/_/nextcloud based on the apache docker-compose.yaml

```
version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:10.5.11
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
```

but I'm not sure how or where the installation of youtube-dl and aria2c will fit into this.
